name: build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main, dotnet-vnext ]
  workflow_dispatch:

env:
  ARTIFACTS_PATH: ./artifacts
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  MACOS_APP_NAME: HelloWorld.app
  MACOS_APP_PATH: ./artifacts/HelloWorld.app
  NUGET_XMLDOC_MODE: skip

permissions: {}

jobs:
  build:
    name: build
    runs-on: macos-latest

    permissions:
      contents: read

    steps:

    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1

    - name: Build and publish
      shell: pwsh
      run: ./build.ps1

    - name: Publish artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: app
        path: ${{ env.ARTIFACTS_PATH }}

  notarize:
    needs: build
    runs-on: macos-latest
    if: |
      github.event.repository.fork == false &&
      !contains(fromJSON('["dependabot[bot]", "github-actions[bot]", "renovate[bot]"]'), github.event.pull_request.user.login)

    permissions:
      contents: read

    steps:

    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Download artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: app
        path: ${{ env.ARTIFACTS_PATH }}

    - name: Generate macOS app
      shell: pwsh
      run: |
        $Artifacts = "${env:ARTIFACTS_PATH}"
        $AppPath = "${env:MACOS_APP_PATH}"
        $ContentsPath = (Join-Path ${AppPath} "Contents")
        $PublishPath = (Join-Path ${Artifacts} "publish")
        New-Item -Path ${Artifacts} -Name ${env:MACOS_APP_NAME} -ItemType "Directory" | Out-Null
        New-Item -Path ${AppPath} -Name "Contents" -ItemType "Directory" | Out-Null
        New-Item -Path ${ContentsPath} -Name "Resources" -ItemType "Directory" | Out-Null
        Copy-Item -Path ${PublishPath} -Destination (Join-Path ${ContentsPath} "MacOS") -Recurse | Out-Null
        Copy-Item -Path ./src/HelloWorld/Info.plist -Destination ${ContentsPath} | Out-Null

    - name: Configure Xcode
      uses: martincostello/xcode-select@db3d404e6e20374a638c10a68e3d804977ec19cb # node20
      with:
        version: "15.3"

    - name: Import Distribution Certificate
      uses: martincostello/import-signing-certificate@a80a8cdd27ba2b00e0e80480fb66c4149de04061 # node20
      with:
        certificate-data: ${{ secrets.DISTRIBUTION_CERTIFICATE_DATA }}
        certificate-passphrase: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSPHRASE }}
        keychain-name: ''
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

    - name: Sign app
      shell: bash
      env:
        APP_NAME: ${{ env.MACOS_APP_PATH }}
        ENTITLEMENTS: ./src/HelloWorld/HelloWorld.entitlements
        SIGNING_IDENTITY: ${{ secrets.SIGNING_IDENTITY }}
      run: |
        chmod +x "${APP_NAME}/Contents/MacOS/HelloWorld"
        find "${APP_NAME}/Contents/MacOS/" | while read -r fname; do
            if [[ -f "${fname}" ]]; then
                echo "Signing ${fname}"
                codesign --force --timestamp --options=runtime --entitlements "${ENTITLEMENTS}" --sign "${SIGNING_IDENTITY}" "${fname}" || true
            fi
        done
        echo "Signing app file"
        codesign --force --timestamp --options=runtime --entitlements "${ENTITLEMENTS}" --sign "${SIGNING_IDENTITY}" "${APP_NAME}"

    - name: Notarize app
      uses: martincostello/xcode-notarize@b461d5783f3d2e7f94e71296e42804b1f81a9dc7 # zizmor: ignore[stale-action-refs] Points to notarytool branch of deprecated action
      with:
        product-path: ${{ env.MACOS_APP_PATH }}
        apple-id: ${{ secrets.NOTARIZATION_USERNAME }}
        app-password: ${{ secrets.NOTARIZATION_PASSWORD }}
        team-id: ${{ secrets.NOTARIZATION_TEAM_ID }}

    - name: Staple app
      uses: martincostello/xcode-staple@2114e06658d8492882b252406aaa7fee3e75ed85 # node20
      with:
        product-path: ${{ env.MACOS_APP_PATH }}

    - name: Package signed app
      run: ditto -V -c -k --keepParent "${MACOS_APP_PATH}" ./artifacts/HelloWorld-osx-x64.zip

    - name: Publish signed app
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: app-signed
        path: ./artifacts/HelloWorld-osx-x64.zip

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: release
    needs: notarize
    runs-on: macos-latest

    permissions:
      contents: write

    steps:

    - name: Download signed app
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: app-signed

    - name: Create GitHub release
      uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        files: '*.zip'
