name: build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main, dotnet-vnext ]
  workflow_dispatch:

env:
  ARTIFACTS_PATH: ./artifacts
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_NOLOGO: true
  MACOS_APP_NAME: HelloWorld.app
  MACOS_APP_PATH: ./artifacts/HelloWorld.app
  NUGET_XMLDOC_MODE: skip

permissions: {}

jobs:
  build:
    name: build
    runs-on: macos-26

    permissions:
      contents: read

    steps:

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0

    - name: Build and publish
      shell: pwsh
      run: ./build.ps1

    - name: Publish artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: app
        path: ${{ env.ARTIFACTS_PATH }}

  notarize:
    needs: build
    runs-on: macos-26
    if: |
      github.event.repository.fork == false &&
      !contains(fromJSON('["dependabot[bot]", "github-actions[bot]", "renovate[bot]"]'), github.event.pull_request.user.login)

    environment:
      name: notarize
      deployment: false

    permissions:
      contents: read

    steps:

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Download artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: app
        path: ${{ env.ARTIFACTS_PATH }}

    - name: Generate macOS app
      shell: pwsh
      run: |
        $Artifacts = "${env:ARTIFACTS_PATH}"
        $AppPath = "${env:MACOS_APP_PATH}"
        $ContentsPath = (Join-Path ${AppPath} "Contents")
        $PublishPath = (Join-Path ${Artifacts} "publish")
        New-Item -Path ${Artifacts} -Name ${env:MACOS_APP_NAME} -ItemType "Directory" | Out-Null
        New-Item -Path ${AppPath} -Name "Contents" -ItemType "Directory" | Out-Null
        New-Item -Path ${ContentsPath} -Name "Resources" -ItemType "Directory" | Out-Null
        Copy-Item -Path ${PublishPath} -Destination (Join-Path ${ContentsPath} "MacOS") -Recurse | Out-Null
        Copy-Item -Path ./src/HelloWorld/Info.plist -Destination ${ContentsPath} | Out-Null

    - name: Configure Xcode
      uses: martincostello/xcode-select@c47a534da51e7bf0b6e615e4fd656239bc6921e9 # node-24
      with:
        version: "26.5"

    - name: Import Distribution Certificate
      uses: martincostello/import-signing-certificate@f1ddd468fc062c21a26ac949000c97a62ae528b2 # node-24
      with:
        certificate-data: ${{ secrets.DISTRIBUTION_CERTIFICATE_DATA }}
        certificate-passphrase: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSPHRASE }}
        keychain-name: ''
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

    - name: Sign app
      shell: bash
      env:
        APP_NAME: ${{ env.MACOS_APP_PATH }}
        ENTITLEMENTS: ./src/HelloWorld/HelloWorld.entitlements
        SIGNING_IDENTITY: ${{ secrets.SIGNING_IDENTITY }}
      run: |
        chmod +x "${APP_NAME}/Contents/MacOS/HelloWorld"
        find "${APP_NAME}/Contents/MacOS/" | while read -r fname; do
            if [[ -f "${fname}" ]]; then
                echo "Signing ${fname}"
                codesign --force --timestamp --options=runtime --entitlements "${ENTITLEMENTS}" --sign "${SIGNING_IDENTITY}" "${fname}" || true
            fi
        done
        echo "Signing app file"
        codesign --force --timestamp --options=runtime --entitlements "${ENTITLEMENTS}" --sign "${SIGNING_IDENTITY}" "${APP_NAME}"

    - name: Notarize app
      uses: martincostello/xcode-notarize@31dc26aa00c957bf07f29054294471cc619062a2 # notarytool-node-24
      with:
        product-path: ${{ env.MACOS_APP_PATH }}
        apple-id: ${{ secrets.NOTARIZATION_USERNAME }}
        app-password: ${{ secrets.NOTARIZATION_PASSWORD }}
        team-id: ${{ secrets.NOTARIZATION_TEAM_ID }}

    - name: Staple app
      uses: martincostello/xcode-staple@4e4f28c261bee6afa32b137709cdd33242334ba1 # node-24
      with:
        product-path: ${{ env.MACOS_APP_PATH }}

    - name: Package signed app
      run: ditto -V -c -k --keepParent "${MACOS_APP_PATH}" ./artifacts/HelloWorld-osx-x64.zip

    - name: Publish signed app
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: app-signed
        path: ./artifacts/HelloWorld-osx-x64.zip

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: release
    needs: notarize
    runs-on: macos-26

    permissions:
      contents: write

    steps:

    - name: Download signed app
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: app-signed

    - name: Create GitHub release
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "${GITHUB_REF_NAME}" "*.zip" --draft --generate-notes --repo "${GITHUB_REPOSITORY}"
